name       : crossguid
version    : 0.2.2
release    : 3
source     :
    - https://github.com/graeme-hill/crossguid/archive/v0.2.2.tar.gz : 48321928473c682b0cdc7e17bbd3390f79f4b98ab22fef3b81a852dda81fd195
license    : MIT
summary    : Lightweight cross platform C++ GUID/UUID library
component  : programming.library
description: |
    Lightweight cross platform C++ GUID/UUID library
setup      : |
    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    mkdir -p %installroot%/usr/lib64/
    mkdir -p %installroot%/usr/include
    mkdir -p %installroot%/usr/share/licenses/libcrossguid
    install -D -m644 $workdir/solusBuildDir/libxg.so %installroot%/usr/lib64/libxg.so.0
    install -D -m644 Guid.hpp %installroot%/usr/include/guid.hpp
    install -D -m644 LICENSE %installroot%/usr/share/licenses/libcrossguid/LICENSE
    cd %installroot%/usr/lib64/
    ln -s libxg.so.0 libxg.so
