name       : crossguid
version    : 20160429
release    : 1
source     :
    - https://github.com/graeme-hill/crossguid/archive/master.zip : 6513d0ad9c87d5ce4e2c79146ac37204741514db1c6328a8992fa407fb457c14
license    : MIT
summary    : Lightweight cross platform C++ GUID/UUID library
description: |
    Lightweight cross platform C++ GUID/UUID library
patterns   :
    devel:/usr/share
build      : |
    g++ -c guid.cpp -o guid.o $CXXFLAGS -std=c++11 -DGUID_LIBUUID
    ar rvs libcrossguid.a guid.o
    
    g++ -c test.cpp -o test.o $CXXFLAGS  -std=c++11
    g++ -c testmain.cpp -o testmain.o $CXXFLAGS
    g++ test.o guid.o testmain.o -o test $CXXFLAGS -luuid
install    : |
    install -D -m644 libcrossguid.a %installroot%/usr/lib/libcrossguid.a
    install -D -m644 guid.h %installroot%/usr/include/guid.h
    install -D -m644 LICENSE %installroot%/usr/share/licenses/libcrossguid/LICENSE
